#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 15 13:47:30 2021

@author: rafi
"""

def pattern(a):
   if a <= 1:
       return a
   else:
       return(pattern(a-1) + pattern(a-2))
   
def process(b):
    if b <= 0:
        print("HHanya untuk angka yang bernilai positif.")
    else:
       print('Bilangan Fibbonaci ke-', (b),'adalah',pattern(b))

while True:
    try:
        angka = int(input('Masukkan angka bilangan :'))
    except ValueError:
        print('Invalid, angka harus bersifat bulat')
    else:
        process(angka)
